packages:
  - "web"
  - "cms"

overrides:
  path-to-regexp@<6.3.0: "^6.3.0"
  yaml@<2.8.3: ">=2.8.3"
  postcss@<8.5.10: ">=8.5.10"
  qs@<6.15.2: ">=6.15.2"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
